branches:
  - master

language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - make --always-make $VIRTUAL_ENV VENV_PYTHON=python$TRAVIS_PYTHON_VERSION

script:
  - make lint
  - make test
