FROM python:3.6-stretch
WORKDIR /app
RUN python3 -m venv /venv && /venv/bin/pip install --upgrade pip setuptools
COPY . .
RUN /venv/bin/pip install -r requirements-dev.txt
CMD make lint test VIRTUAL_ENV=/venv
